name: nfc_business_card
description: Share your portfolio via NFC business card
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # NFC
  nfc_manager: ^4.1.1
  nfc_manager_ndef: ^1.1.0
  flutter_nfc_kit: ^3.5.1
  
  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.3
  
  # Utils
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  qr_flutter: ^4.1.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#0ea5e9"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
